services:
  catalogdb:
    container_name: catalogdb
    user: postgres
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/